---
# handlers file for proxmox_email

- name: restart_postfix
  ansible.builtin.systemd:
    name: postfix
    state: restarted

- name: postmap_sasl_passwd
  ansible.builtin.command:
    cmd: postmap /etc/postfix/sasl_passwd
  changed_when: true

- name: newaliases
  ansible.builtin.command:
    cmd: newaliases
  changed_when: true
