---
galaxy_info:
  role_name: proxmox_backup
  author: Tonton Jo
  description: Backup and restore Proxmox configurations
  license: GPL-3.0-only
  min_ansible_version: "2.14"
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
  galaxy_tags:
    - proxmox
    - backup
    - restore

dependencies: []
collections:
  - community.general
